import { StyleSheet } from "react-native";

import { colors, radius, shadows, spacing, typography } from "./tokens";

export const styles = StyleSheet.create({
  app: {
    alignSelf: "center",
    backgroundColor: colors.warmWhite,
    flex: 1,
    maxWidth: 480,
    width: "100%",
  },
  mobileViewport: { maxWidth: 480, width: "100%" },
  flex: { flex: 1 },
  inline: {
    alignItems: "center",
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing[2],
  },
  lightSafe: {
    alignItems: "center",
    backgroundColor: colors.warmWhite,
    flex: 1,
  },
  darkSafe: { alignItems: "center", backgroundColor: colors.navy, flex: 1 },
  authSafe: { alignItems: "center", backgroundColor: colors.navy, flex: 1 },
  meta: {
    color: colors.textMuted,
    fontFamily: typography.sans,
    fontSize: 13,
    lineHeight: 19,
  },
  cardTitle: {
    color: colors.navy,
    fontFamily: typography.sans,
    fontSize: 15,
    fontWeight: "700",
  },
  cardEyebrow: {
    color: colors.textTertiary,
    fontFamily: typography.sans,
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 1.1,
    marginBottom: spacing[2],
  },
  label: {
    color: colors.navy,
    fontFamily: typography.sans,
    fontSize: 13,
    fontWeight: "700",
    marginBottom: spacing[2],
    marginTop: spacing[4],
  },
  input: {
    backgroundColor: colors.white,
    borderColor: colors.borderSoft,
    borderRadius: radius.md,
    borderWidth: 1,
    color: colors.navy,
    fontFamily: typography.sans,
    fontSize: 15,
    minHeight: 52,
    paddingHorizontal: spacing[4],
  },
  fieldGroup: { flex: 1 },
  pageTitle: {
    color: colors.navy,
    fontFamily: typography.display,
    fontSize: 25,
    fontWeight: "700",
    lineHeight: 31,
  },
  sectionHeader: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: spacing[3],
    marginTop: spacing[5],
  },
  sectionTitle: {
    color: colors.navy,
    fontFamily: typography.display,
    fontSize: 21,
    fontWeight: "700",
  },
  link: {
    color: colors.info,
    fontFamily: typography.sans,
    fontSize: 13,
    fontWeight: "700",
  },
  centerLink: {
    color: colors.info,
    fontFamily: typography.sans,
    fontSize: 14,
    fontWeight: "700",
    padding: spacing[4],
    textAlign: "center",
  },
  onboarding: { flexGrow: 1, padding: spacing[5], paddingBottom: spacing[6] },
  onboardingTop: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  backLight: {
    alignItems: "center",
    height: 48,
    justifyContent: "center",
    width: 48,
  },
  brandLockup: { alignItems: "center" },
  brandName: {
    color: colors.navy,
    fontFamily: typography.display,
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 4,
    marginTop: 4,
  },
  stepText: {
    color: colors.navy,
    fontFamily: typography.sans,
    fontSize: 16,
    fontWeight: "700",
    marginTop: spacing[6],
    textAlign: "center",
  },
  segmentRow: { flexDirection: "row", gap: spacing[2], marginTop: spacing[3] },
  segment: {
    backgroundColor: colors.gray,
    borderRadius: radius.pill,
    flex: 1,
    height: 5,
  },
  segmentActive: { backgroundColor: colors.amber },
  onboardingIllustration: {
    alignItems: "center",
    height: 210,
    justifyContent: "center",
    marginTop: spacing[6],
  },
  illustrationOrbit: {
    borderColor: colors.sky,
    borderRadius: 90,
    borderStyle: "dashed",
    borderWidth: 1,
    height: 180,
    position: "absolute",
    width: 180,
  },
  illustrationCase: {
    alignItems: "center",
    backgroundColor: colors.sky,
    borderRadius: radius.lg,
    height: 120,
    justifyContent: "center",
    transform: [{ rotate: "-5deg" }],
    width: 90,
  },
  illustrationPlane: {
    alignItems: "center",
    backgroundColor: colors.amber,
    borderRadius: 24,
    height: 48,
    justifyContent: "center",
    position: "absolute",
    right: "24%",
    top: 35,
    width: 48,
  },
  displayTitle: {
    color: colors.navy,
    fontFamily: typography.display,
    fontSize: 35,
    fontWeight: "600",
    lineHeight: 42,
    textAlign: "center",
  },
  displayBody: {
    color: colors.textMuted,
    fontFamily: typography.sans,
    fontSize: 16,
    lineHeight: 24,
    marginTop: spacing[3],
    textAlign: "center",
  },
  onboardingControl: { marginTop: spacing[6] },
  heroInput: {
    backgroundColor: colors.white,
    borderColor: colors.navy,
    borderRadius: radius.md,
    borderWidth: 1.5,
    color: colors.navy,
    fontFamily: typography.sans,
    fontSize: 17,
    minHeight: 62,
    paddingHorizontal: spacing[4],
  },
  choiceSelected: {
    alignItems: "center",
    borderColor: colors.amber,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  choiceTitle: {
    color: colors.navy,
    fontFamily: typography.sans,
    fontSize: 16,
    fontWeight: "700",
  },
  choiceGrid: { flexDirection: "row", gap: spacing[3] },
  roleCard: {
    alignItems: "center",
    flex: 1,
    gap: spacing[2],
    minHeight: 100,
    justifyContent: "center",
  },
  onboardingFooter: { marginTop: "auto", paddingTop: spacing[6] },
  skip: {
    color: colors.textMuted,
    fontFamily: typography.sans,
    fontSize: 13,
    fontWeight: "600",
    padding: spacing[3],
    textAlign: "center",
  },
  profileReady: { alignItems: "center", padding: spacing[5] },
  readyName: {
    color: colors.navy,
    fontFamily: typography.display,
    fontSize: 25,
    fontWeight: "600",
    marginTop: spacing[3],
  },
  authPage: {
    backgroundColor: colors.navy,
    flexGrow: 1,
    justifyContent: "flex-end",
    paddingTop: spacing[8],
  },
  authBrand: { alignItems: "center" },
  authBrandName: {
    color: colors.white,
    fontFamily: typography.display,
    fontSize: 16,
    fontWeight: "700",
    letterSpacing: 5,
    marginTop: spacing[2],
  },
  authIntro: {
    alignItems: "center",
    paddingHorizontal: spacing[5],
    paddingVertical: spacing[8],
  },
  authTitle: {
    color: colors.white,
    fontFamily: typography.display,
    fontSize: 36,
    fontWeight: "600",
    lineHeight: 43,
    textAlign: "center",
  },
  amberDash: {
    backgroundColor: colors.amber,
    borderRadius: radius.pill,
    height: 4,
    marginVertical: spacing[4],
    width: 38,
  },
  authSubtitle: {
    color: colors.textInverseMuted,
    fontFamily: typography.sans,
    fontSize: 16,
    textAlign: "center",
  },
  authSheet: {
    backgroundColor: colors.warmWhite,
    borderTopLeftRadius: radius.xl,
    borderTopRightRadius: radius.xl,
    padding: spacing[5],
    paddingBottom: spacing[8],
  },
  orRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: spacing[3],
    marginVertical: spacing[3],
  },
  orLine: { backgroundColor: colors.gray, flex: 1, height: 1 },
  orText: { color: colors.textMuted, fontFamily: typography.sans },
  authLink: {
    color: colors.info,
    fontFamily: typography.sans,
    fontSize: 14,
    fontWeight: "700",
    padding: spacing[4],
    textAlign: "center",
  },
  createAccount: {
    color: colors.navy,
    fontFamily: typography.sans,
    fontSize: 15,
    fontWeight: "700",
    marginTop: spacing[5],
    textAlign: "center",
    textDecorationColor: colors.amber,
    textDecorationLine: "underline",
  },
  backToMethods: {
    alignItems: "center",
    flexDirection: "row",
    gap: spacing[1],
    marginBottom: spacing[3],
  },
  backToMethodsText: {
    color: colors.info,
    fontFamily: typography.sans,
    fontSize: 13,
    fontWeight: "700",
  },
  homeGreeting: {
    backgroundColor: colors.navy,
    paddingBottom: spacing[8],
    paddingHorizontal: spacing[5],
  },
  greeting: {
    color: colors.white,
    fontFamily: typography.display,
    fontSize: 31,
    fontWeight: "700",
  },
  amberText: { color: colors.amber, fontFamily: typography.display },
  homeContent: {
    marginTop: -18,
    paddingBottom: spacing[6],
    paddingHorizontal: spacing[5],
  },
  searchSummary: {
    alignItems: "center",
    flexDirection: "row",
    gap: spacing[3],
    minHeight: 88,
  },
  searchIcon: {
    alignItems: "center",
    backgroundColor: colors.info,
    borderRadius: 24,
    height: 48,
    justifyContent: "center",
    width: 48,
  },
  searchCopy: { flex: 1 },
  searchRoute: {
    color: colors.navy,
    fontFamily: typography.sans,
    fontSize: 17,
    fontWeight: "800",
  },
  searchMeta: {
    alignItems: "center",
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 4,
  },
  modifyPill: {
    backgroundColor: colors.amber,
    borderRadius: radius.sm,
    paddingHorizontal: spacing[3],
    paddingVertical: 10,
  },
  modifyText: {
    color: colors.navy,
    fontFamily: typography.sans,
    fontSize: 12,
    fontWeight: "700",
  },
  quickGrid: { flexDirection: "row", gap: spacing[3], marginTop: spacing[2] },
  quickCard: {
    alignItems: "center",
    flex: 1,
    flexDirection: "row",
    gap: spacing[3],
    minHeight: 92,
  },
  quickIcon: {
    alignItems: "center",
    borderRadius: 22,
    height: 44,
    justifyContent: "center",
    width: 44,
  },
  quickAmber: { backgroundColor: colors.amber },
  quickSky: { backgroundColor: colors.sky },
  quickTitle: {
    color: colors.navy,
    flex: 1,
    fontFamily: typography.sans,
    fontSize: 16,
    fontWeight: "700",
  },
  tripsContent: {
    marginTop: -12,
    paddingBottom: spacing[6],
    paddingHorizontal: spacing[5],
  },
  filters: {
    marginHorizontal: -spacing[5],
    paddingHorizontal: spacing[5],
    paddingVertical: spacing[4],
  },
  filterChip: {
    alignItems: "center",
    backgroundColor: colors.sky,
    borderRadius: radius.pill,
    flexDirection: "row",
    gap: 5,
    marginRight: spacing[2],
    paddingHorizontal: spacing[4],
    paddingVertical: 11,
  },
  filterActive: { backgroundColor: colors.navy },
  filterText: { color: colors.navy, fontSize: 13, fontWeight: "600" },
  filterTextActive: { color: colors.white },
  travelerHero: { alignItems: "center", marginBottom: spacing[5] },
  largeAvatar: {
    alignItems: "center",
    backgroundColor: colors.avatarWarm,
    borderRadius: 40,
    height: 80,
    justifyContent: "center",
    marginBottom: spacing[3],
    width: 80,
  },
  largeAvatarText: { color: colors.navy, fontSize: 23, fontWeight: "800" },
  ratingRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 4,
    marginTop: spacing[2],
  },
  rating: { color: colors.textMuted, fontSize: 13 },
  detailGrid: { flexDirection: "row", flexWrap: "wrap", gap: spacing[3] },
  detail: {
    backgroundColor: colors.sky,
    borderRadius: radius.sm,
    padding: spacing[3],
    width: "47%",
  },
  detailValue: {
    color: colors.navy,
    fontSize: 13,
    fontWeight: "700",
    marginTop: 4,
  },
  trustPanel: {
    alignItems: "center",
    backgroundColor: colors.sky,
    flexDirection: "row",
    gap: spacing[3],
  },
  flowStep: {
    color: colors.info,
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 0.7,
    marginBottom: spacing[2],
    textTransform: "uppercase",
  },
  flowProgress: {
    backgroundColor: colors.gray,
    borderRadius: radius.pill,
    height: 5,
    marginBottom: spacing[5],
    overflow: "hidden",
  },
  flowProgressFill: {
    backgroundColor: colors.amber,
    height: "100%",
    width: "25%",
  },
  chipGrid: { flexDirection: "row", flexWrap: "wrap", gap: spacing[2] },
  packageChip: {
    backgroundColor: colors.white,
    borderColor: colors.borderSoft,
    borderRadius: radius.pill,
    borderWidth: 1,
    paddingHorizontal: spacing[4],
    paddingVertical: 10,
  },
  packageSelected: { backgroundColor: colors.navy, borderColor: colors.navy },
  packageText: { color: colors.textMuted, fontSize: 13 },
  packageTextSelected: { color: colors.white, fontWeight: "700" },
  stepper: {
    alignItems: "center",
    backgroundColor: colors.white,
    borderColor: colors.borderSoft,
    borderRadius: radius.md,
    borderWidth: 1,
    flexDirection: "row",
    gap: spacing[4],
    justifyContent: "center",
    minHeight: 56,
  },
  stepperControl: { padding: spacing[3] },
  stepperValue: {
    color: colors.navy,
    fontSize: 21,
    fontWeight: "800",
    minWidth: 38,
    textAlign: "center",
  },
  unit: { color: colors.textMuted, fontSize: 13 },
  dimensionRow: { flexDirection: "row", gap: spacing[2] },
  dimensionInput: { flex: 1, fontSize: 12, paddingHorizontal: spacing[2] },
  estimateCard: {
    alignItems: "center",
    backgroundColor: colors.sky,
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: spacing[5],
  },
  estimateRight: { alignItems: "flex-end" },
  total: { color: colors.amberPressed, fontSize: 21, fontWeight: "800" },
  summaryLine: {
    alignItems: "center",
    borderBottomColor: colors.borderSoft,
    borderBottomWidth: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: spacing[3],
  },
  checkRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: spacing[3],
    paddingVertical: spacing[4],
  },
  checkbox: {
    alignItems: "center",
    borderColor: colors.navy,
    borderRadius: radius.xs,
    borderWidth: 1.5,
    height: 24,
    justifyContent: "center",
    width: 24,
  },
  checkboxOn: { backgroundColor: colors.amber },
  checkLabel: { color: colors.textMuted, flex: 1, fontSize: 13 },
  paymentMethod: {
    alignItems: "center",
    flexDirection: "row",
    gap: spacing[3],
  },
  legalNote: {
    color: colors.textTertiary,
    fontSize: 11,
    marginTop: spacing[3],
    textAlign: "center",
  },
  successPage: { alignItems: "stretch", paddingTop: spacing[8] },
  successMark: {
    alignItems: "center",
    alignSelf: "center",
    backgroundColor: colors.sky,
    borderRadius: 48,
    height: 96,
    justifyContent: "center",
    marginBottom: spacing[5],
    width: 96,
  },
  successTitle: {
    color: colors.navy,
    fontFamily: typography.display,
    fontSize: 34,
    fontWeight: "600",
    textAlign: "center",
  },
  searchField: {
    alignItems: "center",
    backgroundColor: colors.white,
    borderColor: colors.borderSoft,
    borderRadius: radius.md,
    borderWidth: 1,
    flexDirection: "row",
    gap: spacing[3],
    marginBottom: spacing[4],
    minHeight: 50,
    paddingHorizontal: spacing[4],
  },
  searchPlaceholder: { color: colors.textTertiary, fontSize: 14 },
  conversation: { alignItems: "center", flexDirection: "row", gap: spacing[3] },
  conversationAvatar: {
    alignItems: "center",
    backgroundColor: colors.sky,
    borderRadius: 24,
    height: 48,
    justifyContent: "center",
    width: 48,
  },
  avatarText: { color: colors.navy, fontSize: 13, fontWeight: "800" },
  conversationEnd: { alignItems: "flex-end", gap: 4 },
  unread: {
    alignItems: "center",
    backgroundColor: colors.amber,
    borderRadius: 10,
    height: 20,
    justifyContent: "center",
    width: 20,
  },
  unreadText: { color: colors.navy, fontSize: 10, fontWeight: "800" },
  contextCard: { marginTop: -10 },
  contextTop: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  contextRef: { color: colors.navy, fontSize: 19, fontWeight: "800" },
  miniTimeline: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: spacing[4],
    position: "relative",
  },
  miniLine: {
    backgroundColor: colors.gray,
    height: 2,
    left: 20,
    position: "absolute",
    right: 20,
  },
  miniDot: {
    alignItems: "center",
    backgroundColor: colors.white,
    borderColor: colors.gray,
    borderRadius: 18,
    borderWidth: 2,
    height: 36,
    justifyContent: "center",
    width: 36,
  },
  miniDotOn: { backgroundColor: colors.navy, borderColor: colors.navy },
  chatBody: { minHeight: 320, paddingVertical: spacing[3] },
  bubble: {
    alignSelf: "flex-start",
    backgroundColor: colors.white,
    borderColor: colors.borderSoft,
    borderRadius: radius.md,
    borderBottomLeftRadius: 4,
    borderWidth: 1,
    marginBottom: spacing[3],
    maxWidth: "78%",
    padding: spacing[3],
    ...shadows.card,
  },
  bubbleMine: {
    alignSelf: "flex-end",
    backgroundColor: colors.sky,
    borderBottomLeftRadius: radius.md,
    borderBottomRightRadius: 4,
  },
  bubbleText: { color: colors.navy, fontSize: 14, lineHeight: 20 },
  bubbleTextMine: { color: colors.navy },
  bubbleTime: {
    color: colors.textTertiary,
    fontSize: 10,
    marginTop: 5,
    textAlign: "right",
  },
  handover: {
    alignItems: "center",
    flexDirection: "row",
    gap: spacing[3],
    marginTop: spacing[4],
  },
  handoverCode: {
    backgroundColor: colors.sky,
    borderRadius: radius.sm,
    color: colors.navy,
    fontFamily: typography.mono,
    fontSize: 20,
    fontWeight: "800",
    padding: spacing[3],
  },
  composer: {
    alignItems: "center",
    flexDirection: "row",
    gap: spacing[2],
    marginTop: spacing[3],
  },
  composerInput: {
    backgroundColor: colors.white,
    borderColor: colors.borderSoft,
    borderRadius: radius.pill,
    borderWidth: 1,
    color: colors.navy,
    flex: 1,
    minHeight: 48,
    paddingHorizontal: spacing[4],
  },
  sendButton: {
    alignItems: "center",
    backgroundColor: colors.amber,
    borderRadius: 24,
    height: 48,
    justifyContent: "center",
    width: 48,
  },
  trackingHero: { overflow: "hidden", padding: 0 },
  trackingTop: {
    alignItems: "flex-start",
    flexDirection: "row",
    justifyContent: "space-between",
    padding: spacing[4],
  },
  trackingRef: {
    color: colors.textMuted,
    fontFamily: typography.mono,
    fontSize: 17,
    marginTop: spacing[2],
  },
  statusPill: {
    alignSelf: "flex-end",
    backgroundColor: colors.sky,
    borderRadius: radius.xs,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  statusText: { color: colors.info, fontSize: 12, fontWeight: "700" },
  arrival: {
    color: colors.textMuted,
    fontSize: 12,
    lineHeight: 17,
    marginTop: spacing[2],
    textAlign: "right",
  },
  map: {
    alignItems: "center",
    backgroundColor: colors.skyMap,
    flexDirection: "row",
    justifyContent: "space-between",
    minHeight: 125,
    paddingHorizontal: spacing[5],
  },
  mapCode: { color: colors.navy, fontSize: 12, fontWeight: "800" },
  mapRoute: {
    alignItems: "center",
    flex: 1,
    flexDirection: "row",
    marginHorizontal: spacing[3],
  },
  mapDash: {
    borderColor: colors.navy,
    borderStyle: "dashed",
    borderTopWidth: 1.5,
    flex: 1,
  },
  mapPlane: {
    alignItems: "center",
    backgroundColor: colors.info,
    borderRadius: 18,
    height: 36,
    justifyContent: "center",
    width: 36,
  },
  timeline: { flexDirection: "row", justifyContent: "space-between" },
  timelineItem: { alignItems: "center", flex: 1 },
  timelineDot: {
    alignItems: "center",
    borderColor: colors.gray,
    borderRadius: 22,
    borderWidth: 2,
    height: 44,
    justifyContent: "center",
    width: 44,
  },
  timelineDotOn: { backgroundColor: colors.navy, borderColor: colors.navy },
  timelineLabel: {
    color: colors.navy,
    fontSize: 11,
    fontWeight: "700",
    marginTop: spacing[2],
  },
  timelineTime: {
    color: colors.textMuted,
    fontSize: 10,
    lineHeight: 14,
    marginTop: 4,
    textAlign: "center",
  },
  travelerRow: { alignItems: "center", flexDirection: "row", gap: spacing[3] },
  mediumAvatar: { height: 58, marginBottom: 0, width: 58 },
  infoTiles: { flexDirection: "row", flexWrap: "wrap", gap: spacing[3] },
  infoTile: {
    alignItems: "center",
    flexDirection: "row",
    gap: spacing[3],
    marginBottom: 0,
    width: "47%",
  },
  tileValueRow: { alignItems: "center", flexDirection: "row", gap: 2 },
  profileCard: { marginTop: -10, padding: spacing[5] },
  profileIdentity: {
    alignItems: "center",
    flexDirection: "row",
    gap: spacing[4],
  },
  profileName: {
    color: colors.navy,
    fontSize: 26,
    fontWeight: "800",
    marginBottom: spacing[2],
  },
  profileMetrics: {
    flexDirection: "row",
    gap: spacing[3],
    marginTop: spacing[4],
  },
  metric: {
    backgroundColor: colors.skyMap,
    borderRadius: radius.md,
    flex: 1,
    padding: spacing[3],
  },
  metricValue: { color: colors.navy, fontSize: 22, fontWeight: "800" },
  settingsCard: { paddingVertical: 0 },
  settingRow: {
    alignItems: "center",
    borderBottomColor: colors.borderSoft,
    borderBottomWidth: 1,
    flexDirection: "row",
    gap: spacing[3],
    minHeight: 62,
  },
  settingRowLast: { borderBottomWidth: 0 },
  settingIcon: {
    alignItems: "center",
    backgroundColor: colors.sky,
    borderRadius: radius.sm,
    height: 36,
    justifyContent: "center",
    width: 36,
  },
  activeShipment: { backgroundColor: colors.skyMap },
  logout: {
    color: colors.danger,
    fontSize: 14,
    fontWeight: "700",
    padding: spacing[5],
    textAlign: "center",
  },
  notification: { alignItems: "center", flexDirection: "row", gap: spacing[3] },
});
