import React, { useState } from 'react';
import { Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';

import {
  AppHeader, BottomNavigation, Button, Card, LogoMark, RouteSummary, Screen,
  ScreenFrame, Trip, TripCard, VerifiedBadge,
} from '@/design-system/components';
import { colors, radius, shadows, spacing, typography } from '@/design-system/tokens';

const trips: Trip[] = [
  { name: 'Sarah M.', date: '20 juin', kg: '23 kg disponibles', price: '85 $', rating: '4,9', initials: 'SM', avatarTone: colors.avatarWarm },
  { name: 'Yann K.', date: '22 juin', kg: '15 kg disponibles', price: '70 $', rating: '4,8', initials: 'YK', avatarTone: colors.skyMap },
  { name: 'Mohamed B.', date: '24 juin', kg: '30 kg disponibles', price: '95 $', rating: '4,9', initials: 'MB', avatarTone: colors.gray },
];

function Field({ label, placeholder, value, onChangeText, secure = false }: { label: string; placeholder: string; value?: string; onChangeText?: (value: string) => void; secure?: boolean }) {
  return <View style={styles.fieldGroup}><Text style={styles.label}>{label}</Text><TextInput accessibilityLabel={label} onChangeText={onChangeText} placeholder={placeholder} placeholderTextColor={colors.textTertiary} secureTextEntry={secure} style={styles.input} value={value} /></View>;
}

function SectionTitle({ title, action, onPress }: { title: string; action?: string; onPress?: () => void }) {
  return <View style={styles.sectionHeader}><Text style={styles.sectionTitle}>{title}</Text>{action && onPress && <Pressable accessibilityRole="button" onPress={onPress}><Text style={styles.link}>{action}</Text></Pressable>}</View>;
}

function SearchSummary({ onPress }: { onPress: () => void }) {
  return <Card onPress={onPress} style={styles.searchSummary}><View style={styles.searchIcon}><Text style={styles.searchIconText}>✈</Text></View><View style={styles.searchCopy}><Text style={styles.searchRoute}>Montréal → Abidjan</Text><Text style={styles.meta}>▣ 20 juin   ·   ▱ 12 kg</Text></View><View style={styles.modifyPill}><Text style={styles.modifyText}>Modifier</Text></View></Card>;
}

function Onboarding({ go }: { go: (screen: Screen) => void }) {
  const [step, setStep] = useState(0);
  const [name, setName] = useState('');
  const steps = [
    { title: 'Comment vous appelez-vous ?', body: 'Votre nom nous aide à personnaliser votre expérience.', symbol: 'ID' },
    { title: 'Où êtes-vous situé ?', body: 'Nous adapterons les trajets et les formats à votre pays.', symbol: 'CA' },
    { title: 'Choisissez votre rôle', body: 'Vous pourrez changer de mode à tout moment.', symbol: '⇄' },
    { title: 'Votre numéro de téléphone', body: 'Il servira à sécuriser votre compte.', symbol: '+1' },
    { title: 'Vérifiez votre identité', body: 'La confiance protège chaque envoi CONNECTED.', symbol: '✓' },
    { title: 'Bienvenue dans CONNECTED', body: 'Votre profil est prêt pour votre premier trajet.', symbol: '✓' },
  ];
  const current = steps[step];
  return <SafeAreaView style={styles.lightSafe}><ScrollView contentContainerStyle={styles.onboarding} keyboardShouldPersistTaps="handled" style={styles.mobileViewport}>
    <View style={styles.onboardingTop}><Pressable accessibilityLabel="Retour" onPress={() => step > 0 && setStep(step - 1)} style={styles.backLight}><Text style={styles.backLightText}>‹</Text></Pressable><View style={styles.brandLockup}><LogoMark size={34} /><Text style={styles.brandName}>CONNECTED</Text></View><View style={styles.backLight} /></View>
    <Text style={styles.stepText}>{step + 1} sur 6</Text><View style={styles.segmentRow}>{steps.map((_, index) => <View key={index} style={[styles.segment, index <= step && styles.segmentActive]} />)}</View>
    <View style={styles.onboardingIllustration}><View style={styles.illustrationOrbit} /><View style={styles.illustrationCase}><Text style={styles.illustrationSymbol}>{current.symbol}</Text></View><View style={styles.illustrationPlane}><Text style={styles.illustrationPlaneText}>✈</Text></View></View>
    <Text style={styles.displayTitle}>{current.title}</Text><Text style={styles.displayBody}>{current.body}</Text>
    <View style={styles.onboardingControl}>
      {step === 0 && <TextInput accessibilityLabel="Nom complet" onChangeText={setName} placeholder="Nom complet" placeholderTextColor={colors.textTertiary} style={styles.heroInput} value={name} />}
      {step === 1 && <Card style={styles.choiceSelected}><Text style={styles.choiceTitle}>Canada</Text><Text style={styles.choiceCheck}>✓</Text></Card>}
      {step === 2 && <View style={styles.choiceGrid}><Card style={styles.roleCard}><Text style={styles.roleIcon}>□</Text><Text style={styles.choiceTitle}>Expéditeur</Text></Card><Card style={styles.roleCard}><Text style={styles.roleIcon}>✈</Text><Text style={styles.choiceTitle}>Convoyeur</Text></Card></View>}
      {step === 3 && <TextInput accessibilityLabel="Numéro de téléphone" placeholder="+1 514 000 0000" placeholderTextColor={colors.textTertiary} style={styles.heroInput} />}
      {step === 4 && <Card style={styles.trustPanel}><Text style={styles.trustIcon}>✓</Text><View style={styles.flex}><Text style={styles.cardTitle}>Identité protégée</Text><Text style={styles.meta}>Vérification simulée dans ce prototype</Text></View></Card>}
      {step === 5 && <Card style={styles.profileReady}><VerifiedBadge label="Profil créé" /><Text style={styles.readyName}>{name || 'Franck O.'}</Text><Text style={styles.meta}>Expéditeur · Canada</Text></Card>}
    </View>
    <View style={styles.onboardingFooter}><Button title={step === 5 ? 'Découvrir CONNECTED  →' : 'Continuer  →'} onPress={() => step === 5 ? go('login') : setStep(step + 1)} /><Pressable onPress={() => go('login')}><Text style={styles.skip}>Passer</Text></Pressable></View>
  </ScrollView></SafeAreaView>;
}

function Login({ go }: { go: (screen: Screen) => void }) {
  const [method, setMethod] = useState<'choice' | 'email' | 'phone'>('choice');
  return <SafeAreaView style={styles.authSafe}><ScrollView contentContainerStyle={styles.authPage} keyboardShouldPersistTaps="handled" style={styles.mobileViewport}>
    <View style={styles.authBrand}><LogoMark inverse size={54} /><Text style={styles.authBrandName}>CONNECTED</Text></View>
    <View style={styles.authIntro}><Text style={styles.authTitle}>{method === 'choice' ? 'Bienvenue sur\nCONNECTED' : method === 'email' ? 'Connexion par e-mail' : 'Connexion par téléphone'}</Text><View style={styles.amberDash} /><Text style={styles.authSubtitle}>{method === 'choice' ? 'Envoyez. Voyagez. Connectez-vous.' : 'Retrouvez vos trajets et vos envois.'}</Text></View>
    <View style={styles.authSheet}>{method === 'choice' ? <><Button title="Continuer avec Apple" variant="outline" onPress={() => setMethod('email')} /><Button title="Continuer avec Google" variant="outline" onPress={() => setMethod('email')} /><View style={styles.orRow}><View style={styles.orLine} /><Text style={styles.orText}>ou</Text><View style={styles.orLine} /></View><Button title="Continuer avec un e-mail" variant="secondary" onPress={() => setMethod('email')} /><Pressable onPress={() => setMethod('phone')}><Text style={styles.authLink}>Continuer par téléphone</Text></Pressable></> : <><Pressable onPress={() => setMethod('choice')}><Text style={styles.backToMethods}>‹ Toutes les méthodes</Text></Pressable><Field label={method === 'email' ? 'Adresse e-mail' : 'Numéro de téléphone'} placeholder={method === 'email' ? 'franck@email.com' : '+1 514 000 0000'} /><Field label="Mot de passe" placeholder="••••••••" secure /><Button title="Se connecter" onPress={() => go('home')} /></>}<Pressable onPress={() => go('home')}><Text style={styles.createAccount}>Créer un compte</Text></Pressable></View>
  </ScrollView></SafeAreaView>;
}

function Home({ go }: { go: (screen: Screen) => void }) {
  return <SafeAreaView style={styles.darkSafe}><View style={styles.app}><AppHeader mode /><View style={styles.homeGreeting}><Text style={styles.greeting}>Bonjour, <Text style={styles.amberText}>Franck</Text></Text></View><ScrollView contentContainerStyle={styles.homeContent}><SearchSummary onPress={() => go('trips')} /><View style={styles.quickGrid}><Card onPress={() => go('shipment')} style={styles.quickCard}><View style={[styles.quickIcon, styles.quickAmber]}><Text style={styles.quickGlyph}>□</Text></View><Text style={styles.quickTitle}>Envoyer</Text><Text style={styles.quickArrow}>›</Text></Card><Card onPress={() => go('tracking')} style={styles.quickCard}><View style={[styles.quickIcon, styles.quickSky]}><Text style={styles.quickGlyph}>⌖</Text></View><Text style={styles.quickTitle}>Suivre</Text><Text style={styles.quickArrow}>›</Text></Card></View><SectionTitle action="Voir tout" onPress={() => go('trips')} title="Trajets disponibles" />{trips.map((trip) => <TripCard key={trip.name} onPress={() => go('trip')} trip={trip} />)}</ScrollView><BottomNavigation active="home" go={go} /></View></SafeAreaView>;
}

function Trips({ go }: { go: (screen: Screen) => void }) {
  return <SafeAreaView style={styles.darkSafe}><View style={styles.app}><AppHeader mode title="Trajets" /><ScrollView contentContainerStyle={styles.tripsContent}><SearchSummary onPress={() => go('shipment')} /><ScrollView horizontal showsHorizontalScrollIndicator={false} style={styles.filters}>{['Tous', '✓ Vérifiés', '▣ Aujourd’hui', '⇅ Prix'].map((filter, index) => <View key={filter} style={[styles.filterChip, index === 0 && styles.filterActive]}><Text style={[styles.filterText, index === 0 && styles.filterTextActive]}>{filter}</Text></View>)}</ScrollView><SectionTitle title="Trajets disponibles" />{trips.map((trip, index) => <TripCard key={trip.name} onPress={() => go('trip')} recommended={index === 0} trip={trip} />)}</ScrollView><BottomNavigation active="trips" go={go} /></View></SafeAreaView>;
}

function Detail({ label, value }: { label: string; value: string }) { return <View style={styles.detail}><Text style={styles.meta}>{label}</Text><Text style={styles.detailValue}>{value}</Text></View>; }

function TripDetail({ go }: { go: (screen: Screen) => void }) {
  return <ScreenFrame go={go} title="Détails du trajet"><View style={styles.travelerHero}><View style={[styles.largeAvatar, { backgroundColor: trips[0].avatarTone }]}><Text style={styles.largeAvatarText}>SM</Text></View><Text style={styles.pageTitle}>Sarah M.</Text><VerifiedBadge /><Text style={styles.rating}>★ 4,9 · 18 livraisons réussies</Text></View><Card><Text style={styles.cardEyebrow}>TRAJET SÉLECTIONNÉ</Text><RouteSummary /><View style={styles.detailGrid}><Detail label="Départ" value="20 juin, 08:30" /><Detail label="Arrivée" value="21 juin, 09:15" /><Detail label="Capacité" value="23 kg disponibles" /><Detail label="Tarif" value="85 $ CAD" /></View></Card><Card style={styles.trustPanel}><Text style={styles.trustIcon}>✓</Text><View style={styles.flex}><Text style={styles.cardTitle}>Voyageuse vérifiée</Text><Text style={styles.meta}>Identité contrôlée · Paiement protégé</Text></View></Card><Button title="Réserver avec Sarah" onPress={() => go('reservation')} /><Pressable onPress={() => go('chat')}><Text style={styles.centerLink}>Poser une question à Sarah</Text></Pressable></ScreenFrame>;
}

function Shipment({ go }: { go: (screen: Screen) => void }) {
  const [kg, setKg] = useState('12');
  return <ScreenFrame go={go} title="Expédier un colis"><Text style={styles.flowStep}>Étape 1 sur 4</Text><View style={styles.flowProgress}><View style={styles.flowProgressFill} /></View><Text style={styles.pageTitle}>Parlez-nous de votre colis</Text><Text style={styles.label}>Type de colis</Text><View style={styles.chipGrid}>{['Documents', 'Vêtements', 'Électronique', 'Autre'].map((item) => <View key={item} style={[styles.packageChip, item === 'Vêtements' && styles.packageSelected]}><Text style={[styles.packageText, item === 'Vêtements' && styles.packageTextSelected]}>{item}</Text></View>)}</View><Text style={styles.label}>Poids du colis</Text><View style={styles.stepper}><Pressable onPress={() => setKg(String(Math.max(1, Number(kg) - 1)))}><Text style={styles.stepperButton}>−</Text></Pressable><TextInput keyboardType="numeric" onChangeText={setKg} style={styles.stepperValue} value={kg} /><Text style={styles.unit}>kg</Text><Pressable onPress={() => setKg(String(Number(kg) + 1))}><Text style={styles.stepperButton}>+</Text></Pressable></View><Text style={styles.label}>Dimensions</Text><View style={styles.dimensionRow}>{['Longueur', 'Largeur', 'Hauteur'].map((item) => <TextInput key={item} placeholder={item} placeholderTextColor={colors.textTertiary} style={[styles.input, styles.dimensionInput]} />)}</View><Field label="Description" placeholder="Décrivez le contenu de votre colis" /><Card style={styles.estimateCard}><View><Text style={styles.meta}>Valeur déclarée</Text><Text style={styles.cardTitle}>100 $ CAD</Text></View><View style={styles.estimateRight}><Text style={styles.meta}>Total estimé</Text><Text style={styles.total}>60 $ CAD</Text></View></Card><Button title="Trouver un voyageur" onPress={() => go('reservation')} /></ScreenFrame>;
}

function Reservation({ go }: { go: (screen: Screen) => void }) {
  const [accepted, setAccepted] = useState(false);
  return <ScreenFrame go={go} title="Confirmer ce trajet"><Text style={styles.flowStep}>Étape 3 sur 4 · 75 %</Text><View style={styles.flowProgress}><View style={[styles.flowProgressFill, { width: '75%' }]} /></View><TripCard onPress={() => go('trip')} recommended trip={trips[0]} /><Card><Text style={styles.cardEyebrow}>VOTRE RÉSERVATION</Text><RouteSummary />{[['Votre colis', '12 kg · Vêtements'], ['Transport', '75 $'], ['Frais de service', '10 $'], ['Total', '85 $ CAD']].map(([label, value]) => <View key={label} style={styles.summaryLine}><Text style={styles.meta}>{label}</Text><Text style={label === 'Total' ? styles.total : styles.cardTitle}>{value}</Text></View>)}</Card><Pressable accessibilityRole="checkbox" accessibilityState={{ checked: accepted }} onPress={() => setAccepted(!accepted)} style={styles.checkRow}><View style={[styles.checkbox, accepted && styles.checkboxOn]}><Text style={styles.checkboxMark}>{accepted ? '✓' : ''}</Text></View><Text style={styles.checkLabel}>J’accepte les règles relatives aux objets autorisés</Text></Pressable><Button disabled={!accepted} title="Continuer vers le paiement" onPress={() => go('payment')} /></ScreenFrame>;
}

function Payment({ go }: { go: (screen: Screen) => void }) { return <ScreenFrame go={go} title="Paiement sécurisé"><Card style={styles.trustPanel}><Text style={styles.trustIcon}>⌾</Text><View style={styles.flex}><Text style={styles.cardTitle}>Paiement protégé</Text><Text style={styles.meta}>Fonds conservés jusqu’à la livraison</Text></View></Card><Card><Text style={styles.cardEyebrow}>RÉCAPITULATIF</Text><View style={styles.summaryLine}><Text style={styles.meta}>Montréal → Abidjan</Text><Text style={styles.cardTitle}>85 $ CAD</Text></View><View style={styles.summaryLine}><Text style={styles.meta}>Colis CNCT-7821</Text><Text style={styles.cardTitle}>12 kg</Text></View></Card><Text style={styles.label}>Moyen de paiement</Text><Card style={styles.paymentMethod}><Text style={styles.paymentIcon}>▣</Text><Text style={[styles.cardTitle, styles.flex]}>Carte •••• 4242</Text><Text style={styles.link}>Modifier</Text></Card><Button title="Payer 85 $ CAD" onPress={() => go('done')} /><Text style={styles.legalNote}>Simulation locale — aucun débit réel</Text></ScreenFrame>; }

function Success({ go, published = false }: { go: (screen: Screen) => void; published?: boolean }) { return <ScreenFrame go={go} title={published ? 'C’est publié' : 'Réservation confirmée'}><View style={styles.successPage}><View style={styles.successMark}><Text style={styles.successGlyph}>✓</Text></View><Text style={styles.successTitle}>{published ? 'Votre trajet est en ligne' : 'C’est confirmé !'}</Text><Text style={styles.displayBody}>{published ? 'Vous serez notifié dès qu’une demande compatible est proposée.' : 'Votre réservation Montréal → Abidjan est enregistrée sous la référence CNCT-7821.'}</Text><Button title={published ? 'Voir mes annonces' : 'Voir mon envoi'} onPress={() => go(published ? 'profile' : 'tracking')} />{!published && <Button title="Retour à l’accueil" variant="outline" onPress={() => go('home')} />}</View></ScreenFrame>; }

function Publish({ go }: { go: (screen: Screen) => void }) { return <ScreenFrame go={go} title="Proposer un trajet"><Text style={styles.flowStep}>Nouveau trajet</Text><Text style={styles.pageTitle}>Publiez votre espace disponible</Text><View style={styles.dimensionRow}><View style={styles.flex}><Field label="Départ" placeholder="Montréal" /></View><View style={styles.flex}><Field label="Destination" placeholder="Abidjan" /></View></View><Field label="Date de départ" placeholder="20 juin 2026" /><Field label="Capacité disponible" placeholder="20 kg" /><Field label="Prix par kilogramme" placeholder="45 $ CAD" /><Button title="Publier le trajet" onPress={() => go('published')} /></ScreenFrame>; }

function Messages({ go }: { go: (screen: Screen) => void }) {
  const conversations = [['Sarah M.', 'Votre colis est bien pris en charge', '10:33', '2'], ['Awa T.', 'J’ai encore 2 places disponibles', 'Hier', ''], ['Ibrahim K.', 'Merci pour votre confiance', 'Lun', '1']];
  return <ScreenFrame active="messages" go={go} showNav title="Messages"><View style={styles.searchField}><Text style={styles.searchGlyph}>⌕</Text><Text style={styles.searchPlaceholder}>Rechercher une conversation</Text></View>{conversations.map(([name, message, time, unread]) => <Card key={name} onPress={() => go('chat')} style={styles.conversation}><View style={styles.conversationAvatar}><Text style={styles.avatarText}>{name.split(' ').map((part) => part[0]).join('')}</Text></View><View style={styles.flex}><Text style={styles.cardTitle}>{name}</Text><Text numberOfLines={1} style={styles.meta}>{message}</Text></View><View style={styles.conversationEnd}><Text style={styles.meta}>{time}</Text>{unread && <View style={styles.unread}><Text style={styles.unreadText}>{unread}</Text></View>}</View></Card>)}</ScreenFrame>;
}

function Chat({ go }: { go: (screen: Screen) => void }) {
  const [draft, setDraft] = useState(''); const [messages, setMessages] = useState(['Bonjour Franck, votre colis est bien pris en charge.', 'Parfait, on se retrouve au terminal 1.']);
  return <ScreenFrame active="messages" go={go} showNav title="Sarah M."><Card style={styles.contextCard}><View style={styles.contextTop}><View><Text style={styles.contextRef}>CNCT-7821</Text><Text style={styles.meta}>12 kg · Montréal → Abidjan</Text></View><Button compact title="Suivi" onPress={() => go('tracking')} /></View><View style={styles.miniTimeline}><View style={styles.miniLine} />{['✓', '✓', '✈', '○'].map((item, index) => <View key={index} style={[styles.miniDot, index < 3 && styles.miniDotOn]}><Text style={styles.miniDotText}>{item}</Text></View>)}</View></Card><View style={styles.chatBody}>{messages.map((message, index) => <View key={`${message}-${index}`} style={[styles.bubble, index % 2 === 1 && styles.bubbleMine]}><Text style={[styles.bubbleText, index % 2 === 1 && styles.bubbleTextMine]}>{message}</Text><Text style={styles.bubbleTime}>10:3{index}</Text></View>)}<Card style={styles.handover}><Text style={styles.trustIcon}>▣</Text><View style={styles.flex}><Text style={styles.cardTitle}>Code de remise</Text><Text style={styles.meta}>À montrer à la livraison</Text></View><Text style={styles.handoverCode}>•• 48</Text></Card></View><View style={styles.composer}><TextInput onChangeText={setDraft} placeholder="Message à Sarah" placeholderTextColor={colors.textTertiary} style={styles.composerInput} value={draft} /><Pressable accessibilityLabel="Envoyer" onPress={() => { if (draft.trim()) { setMessages([...messages, draft.trim()]); setDraft(''); } }} style={styles.sendButton}><Text style={styles.sendIcon}>➤</Text></Pressable></View></ScreenFrame>;
}

function Tracking({ go }: { go: (screen: Screen) => void }) {
  const events = [['Réservé', '18 juin\n08:30'], ['Remis', '20 juin\n12:45'], ['En route', '21 juin\n09:15'], ['Livré', '—']];
  return <ScreenFrame go={go} title="Envoi actif"><Card style={styles.trackingHero}><View style={styles.trackingTop}><View><Text style={styles.pageTitle}>Montréal → Abidjan</Text><Text style={styles.trackingRef}>CNCT-7821</Text></View><View><View style={styles.statusPill}><Text style={styles.statusText}>En route</Text></View><Text style={styles.arrival}>Arrivée{'\n'}21 juin</Text></View></View><View style={styles.map}><Text style={styles.mapCode}>YUL</Text><View style={styles.mapRoute}><View style={styles.mapDash} /><View style={styles.mapPlane}><Text style={styles.mapPlaneText}>✈</Text></View><View style={styles.mapDash} /></View><Text style={styles.mapCode}>ABJ</Text></View></Card><Card><View style={styles.timeline}>{events.map(([label, time], index) => <View key={label} style={styles.timelineItem}><View style={[styles.timelineDot, index < 3 && styles.timelineDotOn]}><Text style={[styles.timelineDotText, index < 3 && styles.timelineDotTextOn]}>{index < 3 ? (index === 2 ? '✈' : '✓') : '○'}</Text></View><Text style={styles.timelineLabel}>{label}</Text><Text style={styles.timelineTime}>{time}</Text></View>)}</View></Card><Card style={styles.travelerRow}><View style={[styles.largeAvatar, styles.mediumAvatar]}><Text style={styles.avatarText}>SM</Text></View><View style={styles.flex}><View style={styles.inline}><Text style={styles.cardTitle}>Sarah M.</Text><VerifiedBadge /></View><Text style={styles.meta}>Dernière mise à jour · Aéroport de Montréal</Text></View><Button compact title="Message" onPress={() => go('chat')} /></Card><View style={styles.infoTiles}>{[['▱', 'Poids', '12 kg'], ['□', 'Contenu', 'Vêtements'], ['⌂', 'Remise', 'Terminal 1'], ['▦', 'Code QR', 'Afficher ›']].map(([icon, label, value]) => <Card key={label} style={styles.infoTile}><Text style={styles.tileIcon}>{icon}</Text><View><Text style={styles.meta}>{label}</Text><Text style={styles.cardTitle}>{value}</Text></View></Card>)}</View></ScreenFrame>;
}

function Profile({ go }: { go: (screen: Screen) => void }) {
  const settings = [['✓', 'Vérifier mon identité'], ['□', 'Mes envois et trajets'], ['⌖', 'Suivi en temps réel'], ['▤', 'Preuves et reçus'], ['▣', 'Paiements'], ['?', 'Aide et sécurité']];
  return <ScreenFrame active="profile" go={go} showNav title="Profil"><Card style={styles.profileCard}><View style={styles.profileIdentity}><View style={[styles.largeAvatar, { backgroundColor: colors.skyMap }]}><Text style={styles.largeAvatarText}>FO</Text></View><View style={styles.flex}><Text style={styles.profileName}>Franck O.</Text><VerifiedBadge label="Identité vérifiée" /><Text style={styles.rating}>★ 4,8 · Membre depuis 2026</Text></View></View><View style={styles.profileMetrics}><View style={styles.metric}><Text style={styles.metricValue}>3</Text><Text style={styles.meta}>envois actifs</Text></View><View style={styles.metric}><Text style={styles.metricValue}>12</Text><Text style={styles.meta}>trajets suivis</Text></View></View></Card><Card style={styles.settingsCard}>{settings.map(([icon, label], index) => <Pressable key={label} onPress={() => label === 'Suivi en temps réel' ? go('tracking') : undefined} style={[styles.settingRow, index === settings.length - 1 && styles.settingRowLast]}><View style={styles.settingIcon}><Text style={styles.settingGlyph}>{icon}</Text></View><Text style={[styles.cardTitle, styles.flex]}>{label}</Text><Text style={styles.chevron}>›</Text></Pressable>)}</Card><Card onPress={() => go('tracking')} style={styles.activeShipment}><View style={styles.inline}><View style={styles.statusPill}><Text style={styles.statusText}>En cours</Text></View><Text style={styles.contextRef}>CNCT-7821</Text></View><Text style={styles.cardTitle}>Montréal → Abidjan</Text><Text style={styles.link}>Remise confirmée · Voir le suivi</Text></Card><Pressable onPress={() => go('login')}><Text style={styles.logout}>Se déconnecter</Text></Pressable></ScreenFrame>;
}

function Notifications({ go }: { go: (screen: Screen) => void }) { return <ScreenFrame go={go} title="Notifications"><SectionTitle title="Aujourd’hui" />{[['✓', 'Réservation confirmée', 'Montréal → Abidjan'], ['◌', 'Sarah M. vous a envoyé un message', 'On se retrouve au terminal 1'], ['✈', 'Nouveau convoyeur disponible', '18 kg sur Montréal → Abidjan']].map(([icon, title, copy]) => <Card key={title} onPress={() => go(title.includes('message') ? 'chat' : 'tracking')} style={styles.notification}><View style={styles.settingIcon}><Text style={styles.settingGlyph}>{icon}</Text></View><View style={styles.flex}><Text style={styles.cardTitle}>{title}</Text><Text style={styles.meta}>{copy}</Text></View></Card>)}</ScreenFrame>; }

export default function App() {
  const [screen, setScreen] = useState<Screen>('onboarding'); const go = (next: Screen) => setScreen(next);
  if (screen === 'onboarding') return <Onboarding go={go} />; if (screen === 'login') return <Login go={go} />; if (screen === 'home') return <Home go={go} />; if (screen === 'trips') return <Trips go={go} />; if (screen === 'trip') return <TripDetail go={go} />; if (screen === 'shipment') return <Shipment go={go} />; if (screen === 'reservation') return <Reservation go={go} />; if (screen === 'payment') return <Payment go={go} />; if (screen === 'done') return <Success go={go} />; if (screen === 'publish') return <Publish go={go} />; if (screen === 'published') return <Success go={go} published />; if (screen === 'messages') return <Messages go={go} />; if (screen === 'chat') return <Chat go={go} />; if (screen === 'tracking') return <Tracking go={go} />; if (screen === 'profile') return <Profile go={go} />; return <Notifications go={go} />;
}

const styles = StyleSheet.create({
  app: { alignSelf: 'center', backgroundColor: colors.warmWhite, flex: 1, maxWidth: 480, width: '100%' }, mobileViewport: { maxWidth: 480, width: '100%' }, flex: { flex: 1 }, inline: { alignItems: 'center', flexDirection: 'row', flexWrap: 'wrap', gap: spacing[2] }, lightSafe: { alignItems: 'center', backgroundColor: colors.warmWhite, flex: 1 }, darkSafe: { alignItems: 'center', backgroundColor: colors.navy, flex: 1 }, authSafe: { alignItems: 'center', backgroundColor: colors.navy, flex: 1 },
  meta: { color: colors.textMuted, fontFamily: typography.ui, fontSize: 13, lineHeight: 19 }, cardTitle: { color: colors.navy, fontFamily: typography.ui, fontSize: 15, fontWeight: '700' }, cardEyebrow: { color: colors.textTertiary, fontSize: 11, fontWeight: '700', letterSpacing: 1.1, marginBottom: spacing[2] }, label: { color: colors.navy, fontSize: 13, fontWeight: '700', marginBottom: spacing[2], marginTop: spacing[4] }, input: { backgroundColor: colors.white, borderColor: colors.borderSoft, borderRadius: radius.md, borderWidth: 1, color: colors.navy, fontSize: 15, minHeight: 52, paddingHorizontal: spacing[4] }, fieldGroup: { flex: 1 }, pageTitle: { color: colors.navy, fontFamily: typography.ui, fontSize: 25, fontWeight: '800', lineHeight: 31 }, sectionHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginBottom: spacing[3], marginTop: spacing[5] }, sectionTitle: { color: colors.navy, fontSize: 21, fontWeight: '800' }, link: { color: colors.info, fontSize: 13, fontWeight: '700' }, centerLink: { color: colors.info, fontSize: 14, fontWeight: '700', padding: spacing[4], textAlign: 'center' },
  onboarding: { flexGrow: 1, padding: spacing[5], paddingBottom: spacing[6] }, onboardingTop: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' }, backLight: { height: 48, justifyContent: 'center', width: 48 }, backLightText: { color: colors.navy, fontSize: 42, lineHeight: 42 }, brandLockup: { alignItems: 'center' }, brandName: { color: colors.navy, fontSize: 12, fontWeight: '800', letterSpacing: 4, marginTop: 4 }, stepText: { color: colors.navy, fontSize: 16, fontWeight: '700', marginTop: spacing[6], textAlign: 'center' }, segmentRow: { flexDirection: 'row', gap: spacing[2], marginTop: spacing[3] }, segment: { backgroundColor: colors.gray, borderRadius: radius.pill, flex: 1, height: 5 }, segmentActive: { backgroundColor: colors.amber }, onboardingIllustration: { alignItems: 'center', height: 210, justifyContent: 'center', marginTop: spacing[6] }, illustrationOrbit: { borderColor: colors.sky, borderRadius: 90, borderStyle: 'dashed', borderWidth: 1, height: 180, position: 'absolute', width: 180 }, illustrationCase: { alignItems: 'center', backgroundColor: colors.sky, borderRadius: radius.lg, height: 120, justifyContent: 'center', transform: [{ rotate: '-5deg' }], width: 90 }, illustrationSymbol: { color: colors.navy, fontSize: 28, fontWeight: '800' }, illustrationPlane: { alignItems: 'center', backgroundColor: colors.amber, borderRadius: 24, height: 48, justifyContent: 'center', position: 'absolute', right: '24%', top: 35, width: 48 }, illustrationPlaneText: { color: colors.navy, fontSize: 24 }, displayTitle: { color: colors.navy, fontFamily: typography.display, fontSize: 35, fontWeight: '600', lineHeight: 42, textAlign: 'center' }, displayBody: { color: colors.textMuted, fontSize: 16, lineHeight: 24, marginTop: spacing[3], textAlign: 'center' }, onboardingControl: { marginTop: spacing[6] }, heroInput: { backgroundColor: colors.white, borderColor: colors.navy, borderRadius: radius.md, borderWidth: 1.5, color: colors.navy, fontSize: 17, minHeight: 62, paddingHorizontal: spacing[4] }, choiceSelected: { alignItems: 'center', borderColor: colors.amber, flexDirection: 'row', justifyContent: 'space-between' }, choiceTitle: { color: colors.navy, fontSize: 16, fontWeight: '700' }, choiceCheck: { color: colors.success, fontSize: 20, fontWeight: '800' }, choiceGrid: { flexDirection: 'row', gap: spacing[3] }, roleCard: { alignItems: 'center', flex: 1, gap: spacing[2], minHeight: 100, justifyContent: 'center' }, roleIcon: { color: colors.navy, fontSize: 28 }, onboardingFooter: { marginTop: 'auto', paddingTop: spacing[6] }, skip: { color: colors.textMuted, fontSize: 13, fontWeight: '600', padding: spacing[3], textAlign: 'center' }, profileReady: { alignItems: 'center', padding: spacing[5] }, readyName: { color: colors.navy, fontFamily: typography.display, fontSize: 25, fontWeight: '600', marginTop: spacing[3] },
  authPage: { backgroundColor: colors.navy, flexGrow: 1, justifyContent: 'flex-end', paddingTop: spacing[8] }, authBrand: { alignItems: 'center' }, authBrandName: { color: colors.white, fontSize: 16, fontWeight: '700', letterSpacing: 5, marginTop: spacing[2] }, authIntro: { alignItems: 'center', paddingHorizontal: spacing[5], paddingVertical: spacing[8] }, authTitle: { color: colors.white, fontFamily: typography.display, fontSize: 36, fontWeight: '600', lineHeight: 43, textAlign: 'center' }, amberDash: { backgroundColor: colors.amber, borderRadius: radius.pill, height: 4, marginVertical: spacing[4], width: 38 }, authSubtitle: { color: colors.textInverseMuted, fontSize: 16, textAlign: 'center' }, authSheet: { backgroundColor: colors.warmWhite, borderTopLeftRadius: radius.xl, borderTopRightRadius: radius.xl, padding: spacing[5], paddingBottom: spacing[8] }, orRow: { alignItems: 'center', flexDirection: 'row', gap: spacing[3], marginVertical: spacing[3] }, orLine: { backgroundColor: colors.gray, flex: 1, height: 1 }, orText: { color: colors.textMuted }, authLink: { color: colors.info, fontSize: 14, fontWeight: '700', padding: spacing[4], textAlign: 'center' }, createAccount: { color: colors.navy, fontSize: 15, fontWeight: '700', marginTop: spacing[5], textAlign: 'center', textDecorationColor: colors.amber, textDecorationLine: 'underline' }, backToMethods: { color: colors.info, fontSize: 13, fontWeight: '700', marginBottom: spacing[3] },
  homeGreeting: { backgroundColor: colors.navy, paddingBottom: spacing[8], paddingHorizontal: spacing[5] }, greeting: { color: colors.white, fontSize: 31, fontWeight: '800' }, amberText: { color: colors.amber }, homeContent: { marginTop: -18, paddingBottom: spacing[6], paddingHorizontal: spacing[5] }, searchSummary: { alignItems: 'center', flexDirection: 'row', gap: spacing[3], minHeight: 88 }, searchIcon: { alignItems: 'center', backgroundColor: colors.info, borderRadius: 24, height: 48, justifyContent: 'center', width: 48 }, searchIconText: { color: colors.white, fontSize: 23 }, searchCopy: { flex: 1 }, searchRoute: { color: colors.navy, fontSize: 17, fontWeight: '800' }, modifyPill: { backgroundColor: colors.amber, borderRadius: radius.sm, paddingHorizontal: spacing[3], paddingVertical: 10 }, modifyText: { color: colors.navy, fontSize: 12, fontWeight: '700' }, quickGrid: { flexDirection: 'row', gap: spacing[3], marginTop: spacing[2] }, quickCard: { alignItems: 'center', flex: 1, flexDirection: 'row', gap: spacing[3], minHeight: 92 }, quickIcon: { alignItems: 'center', borderRadius: 22, height: 44, justifyContent: 'center', width: 44 }, quickAmber: { backgroundColor: colors.amber }, quickSky: { backgroundColor: colors.sky }, quickGlyph: { color: colors.navy, fontSize: 22 }, quickTitle: { color: colors.navy, flex: 1, fontSize: 16, fontWeight: '700' }, quickArrow: { color: colors.navy, fontSize: 28 },
  tripsContent: { marginTop: -12, paddingBottom: spacing[6], paddingHorizontal: spacing[5] }, filters: { marginHorizontal: -spacing[5], paddingHorizontal: spacing[5], paddingVertical: spacing[4] }, filterChip: { backgroundColor: colors.sky, borderRadius: radius.pill, marginRight: spacing[2], paddingHorizontal: spacing[4], paddingVertical: 11 }, filterActive: { backgroundColor: colors.navy }, filterText: { color: colors.navy, fontSize: 13, fontWeight: '600' }, filterTextActive: { color: colors.white },
  travelerHero: { alignItems: 'center', marginBottom: spacing[5] }, largeAvatar: { alignItems: 'center', backgroundColor: colors.avatarWarm, borderRadius: 40, height: 80, justifyContent: 'center', marginBottom: spacing[3], width: 80 }, largeAvatarText: { color: colors.navy, fontSize: 23, fontWeight: '800' }, rating: { color: colors.textMuted, fontSize: 13, marginTop: spacing[2] }, detailGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing[3] }, detail: { backgroundColor: colors.sky, borderRadius: radius.sm, padding: spacing[3], width: '47%' }, detailValue: { color: colors.navy, fontSize: 13, fontWeight: '700', marginTop: 4 }, trustPanel: { alignItems: 'center', backgroundColor: colors.sky, flexDirection: 'row', gap: spacing[3] }, trustIcon: { color: colors.info, fontSize: 25, fontWeight: '800' },
  flowStep: { color: colors.info, fontSize: 12, fontWeight: '700', letterSpacing: 0.7, marginBottom: spacing[2], textTransform: 'uppercase' }, flowProgress: { backgroundColor: colors.gray, borderRadius: radius.pill, height: 5, marginBottom: spacing[5], overflow: 'hidden' }, flowProgressFill: { backgroundColor: colors.amber, height: '100%', width: '25%' }, chipGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing[2] }, packageChip: { backgroundColor: colors.white, borderColor: colors.borderSoft, borderRadius: radius.pill, borderWidth: 1, paddingHorizontal: spacing[4], paddingVertical: 10 }, packageSelected: { backgroundColor: colors.navy, borderColor: colors.navy }, packageText: { color: colors.textMuted, fontSize: 13 }, packageTextSelected: { color: colors.white, fontWeight: '700' }, stepper: { alignItems: 'center', backgroundColor: colors.white, borderColor: colors.borderSoft, borderRadius: radius.md, borderWidth: 1, flexDirection: 'row', gap: spacing[4], justifyContent: 'center', minHeight: 56 }, stepperButton: { color: colors.navy, fontSize: 26, fontWeight: '600', padding: spacing[3] }, stepperValue: { color: colors.navy, fontSize: 21, fontWeight: '800', minWidth: 38, textAlign: 'center' }, unit: { color: colors.textMuted, fontSize: 13 }, dimensionRow: { flexDirection: 'row', gap: spacing[2] }, dimensionInput: { flex: 1, fontSize: 12, paddingHorizontal: spacing[2] }, estimateCard: { alignItems: 'center', backgroundColor: colors.sky, flexDirection: 'row', justifyContent: 'space-between', marginTop: spacing[5] }, estimateRight: { alignItems: 'flex-end' }, total: { color: colors.amberPressed, fontSize: 21, fontWeight: '800' }, summaryLine: { alignItems: 'center', borderBottomColor: colors.borderSoft, borderBottomWidth: 1, flexDirection: 'row', justifyContent: 'space-between', paddingVertical: spacing[3] }, checkRow: { alignItems: 'center', flexDirection: 'row', gap: spacing[3], paddingVertical: spacing[4] }, checkbox: { alignItems: 'center', borderColor: colors.navy, borderRadius: radius.xs, borderWidth: 1.5, height: 24, justifyContent: 'center', width: 24 }, checkboxOn: { backgroundColor: colors.amber }, checkboxMark: { color: colors.navy, fontWeight: '900' }, checkLabel: { color: colors.textMuted, flex: 1, fontSize: 13 }, paymentMethod: { alignItems: 'center', flexDirection: 'row', gap: spacing[3] }, paymentIcon: { color: colors.navy, fontSize: 22 }, legalNote: { color: colors.textTertiary, fontSize: 11, marginTop: spacing[3], textAlign: 'center' },
  successPage: { alignItems: 'stretch', paddingTop: spacing[8] }, successMark: { alignItems: 'center', alignSelf: 'center', backgroundColor: colors.sky, borderRadius: 48, height: 96, justifyContent: 'center', marginBottom: spacing[5], width: 96 }, successGlyph: { color: colors.navy, fontSize: 44, fontWeight: '800' }, successTitle: { color: colors.navy, fontFamily: typography.display, fontSize: 34, fontWeight: '600', textAlign: 'center' },
  searchField: { alignItems: 'center', backgroundColor: colors.white, borderColor: colors.borderSoft, borderRadius: radius.md, borderWidth: 1, flexDirection: 'row', gap: spacing[3], marginBottom: spacing[4], minHeight: 50, paddingHorizontal: spacing[4] }, searchGlyph: { color: colors.navy, fontSize: 22 }, searchPlaceholder: { color: colors.textTertiary, fontSize: 14 }, conversation: { alignItems: 'center', flexDirection: 'row', gap: spacing[3] }, conversationAvatar: { alignItems: 'center', backgroundColor: colors.sky, borderRadius: 24, height: 48, justifyContent: 'center', width: 48 }, avatarText: { color: colors.navy, fontSize: 13, fontWeight: '800' }, conversationEnd: { alignItems: 'flex-end', gap: 4 }, unread: { alignItems: 'center', backgroundColor: colors.amber, borderRadius: 10, height: 20, justifyContent: 'center', width: 20 }, unreadText: { color: colors.navy, fontSize: 10, fontWeight: '800' },
  contextCard: { marginTop: -10 }, contextTop: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' }, contextRef: { color: colors.navy, fontSize: 19, fontWeight: '800' }, miniTimeline: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginTop: spacing[4], position: 'relative' }, miniLine: { backgroundColor: colors.gray, height: 2, left: 20, position: 'absolute', right: 20 }, miniDot: { alignItems: 'center', backgroundColor: colors.white, borderColor: colors.gray, borderRadius: 18, borderWidth: 2, height: 36, justifyContent: 'center', width: 36 }, miniDotOn: { backgroundColor: colors.navy, borderColor: colors.navy }, miniDotText: { color: colors.white, fontSize: 13 }, chatBody: { minHeight: 320, paddingVertical: spacing[3] }, bubble: { alignSelf: 'flex-start', backgroundColor: colors.white, borderColor: colors.borderSoft, borderRadius: radius.md, borderBottomLeftRadius: 4, borderWidth: 1, marginBottom: spacing[3], maxWidth: '78%', padding: spacing[3], ...shadows.card }, bubbleMine: { alignSelf: 'flex-end', backgroundColor: colors.sky, borderBottomLeftRadius: radius.md, borderBottomRightRadius: 4 }, bubbleText: { color: colors.navy, fontSize: 14, lineHeight: 20 }, bubbleTextMine: { color: colors.navy }, bubbleTime: { color: colors.textTertiary, fontSize: 10, marginTop: 5, textAlign: 'right' }, handover: { alignItems: 'center', flexDirection: 'row', gap: spacing[3], marginTop: spacing[4] }, handoverCode: { backgroundColor: colors.sky, borderRadius: radius.sm, color: colors.navy, fontFamily: typography.mono, fontSize: 20, fontWeight: '800', padding: spacing[3] }, composer: { alignItems: 'center', flexDirection: 'row', gap: spacing[2], marginTop: spacing[3] }, composerInput: { backgroundColor: colors.white, borderColor: colors.borderSoft, borderRadius: radius.pill, borderWidth: 1, color: colors.navy, flex: 1, minHeight: 48, paddingHorizontal: spacing[4] }, sendButton: { alignItems: 'center', backgroundColor: colors.amber, borderRadius: 24, height: 48, justifyContent: 'center', width: 48 }, sendIcon: { color: colors.navy, fontSize: 20 },
  trackingHero: { overflow: 'hidden', padding: 0 }, trackingTop: { alignItems: 'flex-start', flexDirection: 'row', justifyContent: 'space-between', padding: spacing[4] }, trackingRef: { color: colors.textMuted, fontFamily: typography.mono, fontSize: 17, marginTop: spacing[2] }, statusPill: { alignSelf: 'flex-end', backgroundColor: colors.sky, borderRadius: radius.xs, paddingHorizontal: 10, paddingVertical: 6 }, statusText: { color: colors.info, fontSize: 12, fontWeight: '700' }, arrival: { color: colors.textMuted, fontSize: 12, lineHeight: 17, marginTop: spacing[2], textAlign: 'right' }, map: { alignItems: 'center', backgroundColor: colors.skyMap, flexDirection: 'row', justifyContent: 'space-between', minHeight: 125, paddingHorizontal: spacing[5] }, mapCode: { color: colors.navy, fontSize: 12, fontWeight: '800' }, mapRoute: { alignItems: 'center', flex: 1, flexDirection: 'row', marginHorizontal: spacing[3] }, mapDash: { borderColor: colors.navy, borderStyle: 'dashed', borderTopWidth: 1.5, flex: 1 }, mapPlane: { alignItems: 'center', backgroundColor: colors.info, borderRadius: 18, height: 36, justifyContent: 'center', width: 36 }, mapPlaneText: { color: colors.white, fontSize: 17 }, timeline: { flexDirection: 'row', justifyContent: 'space-between' }, timelineItem: { alignItems: 'center', flex: 1 }, timelineDot: { alignItems: 'center', borderColor: colors.gray, borderRadius: 22, borderWidth: 2, height: 44, justifyContent: 'center', width: 44 }, timelineDotOn: { backgroundColor: colors.navy, borderColor: colors.navy }, timelineDotText: { color: colors.textTertiary }, timelineDotTextOn: { color: colors.white }, timelineLabel: { color: colors.navy, fontSize: 11, fontWeight: '700', marginTop: spacing[2] }, timelineTime: { color: colors.textMuted, fontSize: 10, lineHeight: 14, marginTop: 4, textAlign: 'center' }, travelerRow: { alignItems: 'center', flexDirection: 'row', gap: spacing[3] }, mediumAvatar: { height: 58, marginBottom: 0, width: 58 }, infoTiles: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing[3] }, infoTile: { alignItems: 'center', flexDirection: 'row', gap: spacing[3], marginBottom: 0, width: '47%' }, tileIcon: { color: colors.navy, fontSize: 23 },
  profileCard: { marginTop: -10, padding: spacing[5] }, profileIdentity: { alignItems: 'center', flexDirection: 'row', gap: spacing[4] }, profileName: { color: colors.navy, fontSize: 26, fontWeight: '800', marginBottom: spacing[2] }, profileMetrics: { flexDirection: 'row', gap: spacing[3], marginTop: spacing[4] }, metric: { backgroundColor: colors.skyMap, borderRadius: radius.md, flex: 1, padding: spacing[3] }, metricValue: { color: colors.navy, fontSize: 22, fontWeight: '800' }, settingsCard: { paddingVertical: 0 }, settingRow: { alignItems: 'center', borderBottomColor: colors.borderSoft, borderBottomWidth: 1, flexDirection: 'row', gap: spacing[3], minHeight: 62 }, settingRowLast: { borderBottomWidth: 0 }, settingIcon: { alignItems: 'center', backgroundColor: colors.sky, borderRadius: radius.sm, height: 36, justifyContent: 'center', width: 36 }, settingGlyph: { color: colors.navy, fontSize: 17, fontWeight: '700' }, chevron: { color: colors.navy, fontSize: 28 }, activeShipment: { backgroundColor: colors.skyMap }, logout: { color: colors.danger, fontSize: 14, fontWeight: '700', padding: spacing[5], textAlign: 'center' }, notification: { alignItems: 'center', flexDirection: 'row', gap: spacing[3] },
});
